profile: {{ env['AWS_PROFILE'] }}
region: {{ env['AWS_REGION'] }}
versioning: false
default_alias: null
clean_build: true
configuration:
  name: docker-swarm-controller
  runtime: python2.7
  role: arn:aws:iam::027273742350:role/docker-swarm-controller
  handler: lambda_function.lambda_handler
  description: Controll Docker Swarm Service for WordPress
  timeout: 60
  memory_size: 128
