---
default: &default
  Labels:
    Name: docker-s3to-netlify
  Networks:
  - Target: shifter_net_user
  Name: {{ service_name }}
  TaskTemplate:
    ContainerSpec:
      Env:
        {{#envvars}}
        - "{{envvar}}"
        {{/envvars}}
        {{^envvars}}
        - "DUMMY_ENV=True"
        {{/envvars}}
      Image: {{ image_string }}
      Mounts:
      - Target: /run
        Type: tmpfs
      - Target: /tmp
        Type: tmpfs
    LogDriver:
      Name: awslogs
      Options:
        awslogs-group: dockerlog-services
        awslogs-region: us-east-1
        awslogs-stream: {{ service_id }}-s3to-netlify
    Placement:
      Constraints:
        - "node.labels.type == efs-worker"
    RestartPolicy:
      Condition: on-failure
      Delay: 5000
      MaxAttempts: 2

dev:
  <<: *default

prod:
  <<: *default

development:
  <<: *default
  TaskTemplate:
    LogDriver:
      Name: awslogs
      Options:
        awslogs-group: dockerlog-services-development
        awslogs-region: us-east-1
        awslogs-stream: {{ service_id }}-s3to-netlify

production:
  <<: *default
